### PR TITLE
Implement batch_det function

### PR DESCRIPTION
**Pull request by takuseno**
Hi, @TE-AkioHayakawa san, @TE-TakuyaNarihira san.

I've implemented `batch_det` function that computes determinant of input array.

```
a = nn.Variable((2, 13, 13))
det = F.batch_det(a) # det.shape == (2,)

nd = np.random.random((2, 13, 13))
a.d = nd
det.forward()

assert np.allclose(det.d, np.array(list(map(np.linalg.det, nd))))
```

`batch_det` works with forward and backward correctly now. cuda extension is implemented.

### CODE REVIEW

**Comment by takuseno** [comment]
cuda version is implemented https://github.com/sony/nnabla-ext-cuda/pull/132

**Comment by takuseno** [comment]
@TE-KazukiYoshiyama san reviewed this

**Comment by takuseno** [comment]
@TE-AkioHayakawa 
I've resolved conflict. Now, it's ready for merge :)

**Comment by TE-AkioHayakawa** [comment]
@takuseno 
Thanks a lot!
Could you do the same thing for https://github.com/sony/nnabla-ext-cuda/pull/132 ?

**Comment by takuseno** [comment]
@TE-AkioHayakawa 
I've resolved that conflict.  The cuda implementation is ready for merge too :)

**Comment by TE-AkioHayakawa** [comment]
@takuseno 
One more minor thing. Could you update doc/python/api/function.rst?

**Comment by takuseno** [comment]
@TE-AkioHayakawa 
I've added `batch_det` to document. And, squashed version of PR is created as #553 . If you prefer the new PR, I'd like you to see it :)

**Comment by TE-AkioHayakawa** [comment]
@takuseno 
Thanks a lot! It looks Nice!
 I will see #533 and run CI testing again. Please wait a moment.

**Pull request closed without merging**
